// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq9N8zpd1H0Ar49QwVxGMoJLQO28wD2zg',
    appId: '1:727720927438:web:654cbc28eeda930859309f',
    messagingSenderId: '727720927438',
    projectId: 'sportfinder-ea6ba',
    authDomain: 'sportfinder-ea6ba.firebaseapp.com',
    storageBucket: 'sportfinder-ea6ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO2I8tTo7Udmwq74xbUCwC_wd_ZYyPOCc',
    appId: '1:727720927438:ios:c7709c1fbaaa3db959309f',
    messagingSenderId: '727720927438',
    projectId: 'sportfinder-ea6ba',
    storageBucket: 'sportfinder-ea6ba.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO2I8tTo7Udmwq74xbUCwC_wd_ZYyPOCc',
    appId: '1:727720927438:ios:c7709c1fbaaa3db959309f',
    messagingSenderId: '727720927438',
    projectId: 'sportfinder-ea6ba',
    storageBucket: 'sportfinder-ea6ba.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq9N8zpd1H0Ar49QwVxGMoJLQO28wD2zg',
    appId: '1:727720927438:web:fc89b429a1a144f259309f',
    messagingSenderId: '727720927438',
    projectId: 'sportfinder-ea6ba',
    authDomain: 'sportfinder-ea6ba.firebaseapp.com',
    storageBucket: 'sportfinder-ea6ba.firebasestorage.app',
  );
}
